<?xml version="1.0" encoding="utf-8"?><Database Name="GestProgram" Class="ClinicasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVERDEV;Initial Catalog=GestProgram;User ID=cliente" SettingsObjectName="Server.Properties.Settings" SettingsPropertyName="GestProgramConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Clinicas" Member="Clinicas">
    <Type Name="Clinica">
      <Column Name="idClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NomeClinica" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Acesso" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DNS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PassAdministrador" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Estado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>