#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestProgram")]
	public partial class ClinicasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClinicasDataContext() : 
				base(global::Server.Properties.Settings.Default.GestProgramConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clinica> Clinicas
		{
			get
			{
				return this.GetTable<Clinica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clinicas")]
	public partial class Clinica
	{
		
		private int _idClinica;
		
		private string _NomeClinica;
		
		private System.Nullable<bool> _Acesso;
		
		private string _DNS;
		
		private string _PassAdministrador;
		
		private System.Nullable<bool> _Estado;
		
		public Clinica()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClinica", DbType="Int NOT NULL")]
		public int idClinica
		{
			get
			{
				return this._idClinica;
			}
			set
			{
				if ((this._idClinica != value))
				{
					this._idClinica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NomeClinica", DbType="NVarChar(255)")]
		public string NomeClinica
		{
			get
			{
				return this._NomeClinica;
			}
			set
			{
				if ((this._NomeClinica != value))
				{
					this._NomeClinica = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Acesso", DbType="Bit")]
		public System.Nullable<bool> Acesso
		{
			get
			{
				return this._Acesso;
			}
			set
			{
				if ((this._Acesso != value))
				{
					this._Acesso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNS", DbType="NVarChar(255)")]
		public string DNS
		{
			get
			{
				return this._DNS;
			}
			set
			{
				if ((this._DNS != value))
				{
					this._DNS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdministrador", DbType="NVarChar(255)")]
		public string PassAdministrador
		{
			get
			{
				return this._PassAdministrador;
			}
			set
			{
				if ((this._PassAdministrador != value))
				{
					this._PassAdministrador = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
