<?xml version="1.0" encoding="utf-8"?><Database Name="GestMulti" Class="RegistarPostoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVERDEV;Initial Catalog=GestMulti;User ID=cliente" SettingsObjectName="Server.Properties.Settings" SettingsPropertyName="GestMultiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.WorkStation" Member="WorkStations">
    <Type Name="WorkStation">
      <Column Name="id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idClinic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="macAddress" Type="System.String" DbType="NVarChar(250) NOT NULL" CanBeNull="false" />
      <Column Name="uuid" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>