#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestMulti")]
	public partial class ClinicasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertClinica(Clinica instance);
    partial void UpdateClinica(Clinica instance);
    partial void DeleteClinica(Clinica instance);
    #endregion
		
		public ClinicasDataContext() : 
				base(global::Client.Properties.Settings.Default.GestMultiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Clinica> Clinicas
		{
			get
			{
				return this.GetTable<Clinica>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Clinicas")]
	public partial class Clinica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClinica;
		
		private string _EnderecoIP;
		
		private string _DNS;
		
		private string _Porta;
		
		private string _UsernameBD;
		
		private string _PasswordBD;
		
		private string _Nome;
		
		private string _Morada;
		
		private string _Localidade;
		
		private string _CP4;
		
		private string _CP3;
		
		private string _Cidade;
		
		private System.Data.Linq.Binary _Logotipo;
		
		private string _LogotipoCaminho;
		
		private System.Nullable<bool> _Estado;
		
		private string _postalCodeDesignation;
		
		private string _township;
		
		private string _county;
		
		private string _street;
		
		private System.Nullable<int> _number;
		
		private System.Nullable<int> _idCountry;
		
		private string _addressServer;
		
		private System.Nullable<bool> _isActive;
		
		private System.Nullable<int> _createdBy;
		
		private System.Nullable<System.DateTime> _createdAt;
		
		private System.Nullable<int> _updatedBy;
		
		private System.Nullable<System.DateTime> _updatedAt;
		
		private System.Nullable<bool> _isConnect;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClinicaChanging(int value);
    partial void OnidClinicaChanged();
    partial void OnEnderecoIPChanging(string value);
    partial void OnEnderecoIPChanged();
    partial void OnDNSChanging(string value);
    partial void OnDNSChanged();
    partial void OnPortaChanging(string value);
    partial void OnPortaChanged();
    partial void OnUsernameBDChanging(string value);
    partial void OnUsernameBDChanged();
    partial void OnPasswordBDChanging(string value);
    partial void OnPasswordBDChanged();
    partial void OnNomeChanging(string value);
    partial void OnNomeChanged();
    partial void OnMoradaChanging(string value);
    partial void OnMoradaChanged();
    partial void OnLocalidadeChanging(string value);
    partial void OnLocalidadeChanged();
    partial void OnCP4Changing(string value);
    partial void OnCP4Changed();
    partial void OnCP3Changing(string value);
    partial void OnCP3Changed();
    partial void OnCidadeChanging(string value);
    partial void OnCidadeChanged();
    partial void OnLogotipoChanging(System.Data.Linq.Binary value);
    partial void OnLogotipoChanged();
    partial void OnLogotipoCaminhoChanging(string value);
    partial void OnLogotipoCaminhoChanged();
    partial void OnEstadoChanging(System.Nullable<bool> value);
    partial void OnEstadoChanged();
    partial void OnpostalCodeDesignationChanging(string value);
    partial void OnpostalCodeDesignationChanged();
    partial void OntownshipChanging(string value);
    partial void OntownshipChanged();
    partial void OncountyChanging(string value);
    partial void OncountyChanged();
    partial void OnstreetChanging(string value);
    partial void OnstreetChanged();
    partial void OnnumberChanging(System.Nullable<int> value);
    partial void OnnumberChanged();
    partial void OnidCountryChanging(System.Nullable<int> value);
    partial void OnidCountryChanged();
    partial void OnaddressServerChanging(string value);
    partial void OnaddressServerChanged();
    partial void OnisActiveChanging(System.Nullable<bool> value);
    partial void OnisActiveChanged();
    partial void OncreatedByChanging(System.Nullable<int> value);
    partial void OncreatedByChanged();
    partial void OncreatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedAtChanged();
    partial void OnupdatedByChanging(System.Nullable<int> value);
    partial void OnupdatedByChanged();
    partial void OnupdatedAtChanging(System.Nullable<System.DateTime> value);
    partial void OnupdatedAtChanged();
    partial void OnisConnectChanging(System.Nullable<bool> value);
    partial void OnisConnectChanged();
    #endregion
		
		public Clinica()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClinica", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClinica
		{
			get
			{
				return this._idClinica;
			}
			set
			{
				if ((this._idClinica != value))
				{
					this.OnidClinicaChanging(value);
					this.SendPropertyChanging();
					this._idClinica = value;
					this.SendPropertyChanged("idClinica");
					this.OnidClinicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnderecoIP", DbType="VarChar(240)")]
		public string EnderecoIP
		{
			get
			{
				return this._EnderecoIP;
			}
			set
			{
				if ((this._EnderecoIP != value))
				{
					this.OnEnderecoIPChanging(value);
					this.SendPropertyChanging();
					this._EnderecoIP = value;
					this.SendPropertyChanged("EnderecoIP");
					this.OnEnderecoIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNS", DbType="NVarChar(240)")]
		public string DNS
		{
			get
			{
				return this._DNS;
			}
			set
			{
				if ((this._DNS != value))
				{
					this.OnDNSChanging(value);
					this.SendPropertyChanging();
					this._DNS = value;
					this.SendPropertyChanged("DNS");
					this.OnDNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Porta", DbType="NVarChar(250)")]
		public string Porta
		{
			get
			{
				return this._Porta;
			}
			set
			{
				if ((this._Porta != value))
				{
					this.OnPortaChanging(value);
					this.SendPropertyChanging();
					this._Porta = value;
					this.SendPropertyChanged("Porta");
					this.OnPortaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UsernameBD", DbType="NVarChar(50)")]
		public string UsernameBD
		{
			get
			{
				return this._UsernameBD;
			}
			set
			{
				if ((this._UsernameBD != value))
				{
					this.OnUsernameBDChanging(value);
					this.SendPropertyChanging();
					this._UsernameBD = value;
					this.SendPropertyChanged("UsernameBD");
					this.OnUsernameBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordBD", DbType="NVarChar(50)")]
		public string PasswordBD
		{
			get
			{
				return this._PasswordBD;
			}
			set
			{
				if ((this._PasswordBD != value))
				{
					this.OnPasswordBDChanging(value);
					this.SendPropertyChanging();
					this._PasswordBD = value;
					this.SendPropertyChanged("PasswordBD");
					this.OnPasswordBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(50)")]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this.OnNomeChanging(value);
					this.SendPropertyChanging();
					this._Nome = value;
					this.SendPropertyChanged("Nome");
					this.OnNomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morada", DbType="NVarChar(100)")]
		public string Morada
		{
			get
			{
				return this._Morada;
			}
			set
			{
				if ((this._Morada != value))
				{
					this.OnMoradaChanging(value);
					this.SendPropertyChanging();
					this._Morada = value;
					this.SendPropertyChanged("Morada");
					this.OnMoradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidade", DbType="NVarChar(100)")]
		public string Localidade
		{
			get
			{
				return this._Localidade;
			}
			set
			{
				if ((this._Localidade != value))
				{
					this.OnLocalidadeChanging(value);
					this.SendPropertyChanging();
					this._Localidade = value;
					this.SendPropertyChanged("Localidade");
					this.OnLocalidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP4", DbType="NVarChar(50)")]
		public string CP4
		{
			get
			{
				return this._CP4;
			}
			set
			{
				if ((this._CP4 != value))
				{
					this.OnCP4Changing(value);
					this.SendPropertyChanging();
					this._CP4 = value;
					this.SendPropertyChanged("CP4");
					this.OnCP4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP3", DbType="NVarChar(50)")]
		public string CP3
		{
			get
			{
				return this._CP3;
			}
			set
			{
				if ((this._CP3 != value))
				{
					this.OnCP3Changing(value);
					this.SendPropertyChanging();
					this._CP3 = value;
					this.SendPropertyChanged("CP3");
					this.OnCP3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cidade", DbType="NVarChar(50)")]
		public string Cidade
		{
			get
			{
				return this._Cidade;
			}
			set
			{
				if ((this._Cidade != value))
				{
					this.OnCidadeChanging(value);
					this.SendPropertyChanging();
					this._Cidade = value;
					this.SendPropertyChanged("Cidade");
					this.OnCidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logotipo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logotipo
		{
			get
			{
				return this._Logotipo;
			}
			set
			{
				if ((this._Logotipo != value))
				{
					this.OnLogotipoChanging(value);
					this.SendPropertyChanging();
					this._Logotipo = value;
					this.SendPropertyChanged("Logotipo");
					this.OnLogotipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogotipoCaminho", DbType="NVarChar(200)")]
		public string LogotipoCaminho
		{
			get
			{
				return this._LogotipoCaminho;
			}
			set
			{
				if ((this._LogotipoCaminho != value))
				{
					this.OnLogotipoCaminhoChanging(value);
					this.SendPropertyChanging();
					this._LogotipoCaminho = value;
					this.SendPropertyChanged("LogotipoCaminho");
					this.OnLogotipoCaminhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Bit")]
		public System.Nullable<bool> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postalCodeDesignation", DbType="NVarChar(250)")]
		public string postalCodeDesignation
		{
			get
			{
				return this._postalCodeDesignation;
			}
			set
			{
				if ((this._postalCodeDesignation != value))
				{
					this.OnpostalCodeDesignationChanging(value);
					this.SendPropertyChanging();
					this._postalCodeDesignation = value;
					this.SendPropertyChanged("postalCodeDesignation");
					this.OnpostalCodeDesignationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_township", DbType="NVarChar(250)")]
		public string township
		{
			get
			{
				return this._township;
			}
			set
			{
				if ((this._township != value))
				{
					this.OntownshipChanging(value);
					this.SendPropertyChanging();
					this._township = value;
					this.SendPropertyChanged("township");
					this.OntownshipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_county", DbType="NVarChar(250)")]
		public string county
		{
			get
			{
				return this._county;
			}
			set
			{
				if ((this._county != value))
				{
					this.OncountyChanging(value);
					this.SendPropertyChanging();
					this._county = value;
					this.SendPropertyChanged("county");
					this.OncountyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_street", DbType="NVarChar(250)")]
		public string street
		{
			get
			{
				return this._street;
			}
			set
			{
				if ((this._street != value))
				{
					this.OnstreetChanging(value);
					this.SendPropertyChanging();
					this._street = value;
					this.SendPropertyChanged("street");
					this.OnstreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Int")]
		public System.Nullable<int> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCountry", DbType="Int")]
		public System.Nullable<int> idCountry
		{
			get
			{
				return this._idCountry;
			}
			set
			{
				if ((this._idCountry != value))
				{
					this.OnidCountryChanging(value);
					this.SendPropertyChanging();
					this._idCountry = value;
					this.SendPropertyChanged("idCountry");
					this.OnidCountryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_addressServer", DbType="NVarChar(250)")]
		public string addressServer
		{
			get
			{
				return this._addressServer;
			}
			set
			{
				if ((this._addressServer != value))
				{
					this.OnaddressServerChanging(value);
					this.SendPropertyChanging();
					this._addressServer = value;
					this.SendPropertyChanged("addressServer");
					this.OnaddressServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isActive", DbType="Bit")]
		public System.Nullable<bool> isActive
		{
			get
			{
				return this._isActive;
			}
			set
			{
				if ((this._isActive != value))
				{
					this.OnisActiveChanging(value);
					this.SendPropertyChanging();
					this._isActive = value;
					this.SendPropertyChanged("isActive");
					this.OnisActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdBy", DbType="Int")]
		public System.Nullable<int> createdBy
		{
			get
			{
				return this._createdBy;
			}
			set
			{
				if ((this._createdBy != value))
				{
					this.OncreatedByChanging(value);
					this.SendPropertyChanging();
					this._createdBy = value;
					this.SendPropertyChanged("createdBy");
					this.OncreatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> createdAt
		{
			get
			{
				return this._createdAt;
			}
			set
			{
				if ((this._createdAt != value))
				{
					this.OncreatedAtChanging(value);
					this.SendPropertyChanging();
					this._createdAt = value;
					this.SendPropertyChanged("createdAt");
					this.OncreatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedBy", DbType="Int")]
		public System.Nullable<int> updatedBy
		{
			get
			{
				return this._updatedBy;
			}
			set
			{
				if ((this._updatedBy != value))
				{
					this.OnupdatedByChanging(value);
					this.SendPropertyChanging();
					this._updatedBy = value;
					this.SendPropertyChanged("updatedBy");
					this.OnupdatedByChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedAt", DbType="DateTime")]
		public System.Nullable<System.DateTime> updatedAt
		{
			get
			{
				return this._updatedAt;
			}
			set
			{
				if ((this._updatedAt != value))
				{
					this.OnupdatedAtChanging(value);
					this.SendPropertyChanging();
					this._updatedAt = value;
					this.SendPropertyChanged("updatedAt");
					this.OnupdatedAtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isConnect", DbType="Bit")]
		public System.Nullable<bool> isConnect
		{
			get
			{
				return this._isConnect;
			}
			set
			{
				if ((this._isConnect != value))
				{
					this.OnisConnectChanging(value);
					this.SendPropertyChanging();
					this._isConnect = value;
					this.SendPropertyChanged("isConnect");
					this.OnisConnectChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
