#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Linq
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="GestProgram")]
	public partial class ClinicaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClinicaDataContext() : 
				base(global::Client.Properties.Settings.Default.GestProgramConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ClinicaDados> ClinicaDados
		{
			get
			{
				return this.GetTable<ClinicaDados>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ClinicaDados")]
	public partial class ClinicaDados
	{
		
		private int _idClinicaDados;
		
		private string _Nome;
		
		private string _Morada;
		
		private string _Localidade;
		
		private string _CP4;
		
		private string _CP3;
		
		private System.Data.Linq.Binary _Logotipo;
		
		private string _LogotipoCaminho;
		
		private string _EnderecoIP;
		
		private string _DNS;
		
		private System.Nullable<int> _Porta;
		
		private string _UtilizadorBD;
		
		private string _PasswordBD;
		
		private string _PasswordAdmin;
		
		private System.Nullable<int> _idClinicaMulti;
		
		private System.Nullable<System.TimeSpan> _HIM;
		
		private System.Nullable<System.TimeSpan> _HFM;
		
		private System.Nullable<System.TimeSpan> _HIT;
		
		private System.Nullable<System.TimeSpan> _HFT;
		
		public ClinicaDados()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClinicaDados", DbType="Int NOT NULL")]
		public int idClinicaDados
		{
			get
			{
				return this._idClinicaDados;
			}
			set
			{
				if ((this._idClinicaDados != value))
				{
					this._idClinicaDados = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nome", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Nome
		{
			get
			{
				return this._Nome;
			}
			set
			{
				if ((this._Nome != value))
				{
					this._Nome = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Morada", DbType="NVarChar(100)")]
		public string Morada
		{
			get
			{
				return this._Morada;
			}
			set
			{
				if ((this._Morada != value))
				{
					this._Morada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Localidade", DbType="NVarChar(100)")]
		public string Localidade
		{
			get
			{
				return this._Localidade;
			}
			set
			{
				if ((this._Localidade != value))
				{
					this._Localidade = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP4", DbType="NVarChar(50)")]
		public string CP4
		{
			get
			{
				return this._CP4;
			}
			set
			{
				if ((this._CP4 != value))
				{
					this._CP4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CP3", DbType="NVarChar(50)")]
		public string CP3
		{
			get
			{
				return this._CP3;
			}
			set
			{
				if ((this._CP3 != value))
				{
					this._CP3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Logotipo", DbType="VarBinary(MAX)", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Logotipo
		{
			get
			{
				return this._Logotipo;
			}
			set
			{
				if ((this._Logotipo != value))
				{
					this._Logotipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogotipoCaminho", DbType="NVarChar(200)")]
		public string LogotipoCaminho
		{
			get
			{
				return this._LogotipoCaminho;
			}
			set
			{
				if ((this._LogotipoCaminho != value))
				{
					this._LogotipoCaminho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnderecoIP", DbType="NVarChar(240)")]
		public string EnderecoIP
		{
			get
			{
				return this._EnderecoIP;
			}
			set
			{
				if ((this._EnderecoIP != value))
				{
					this._EnderecoIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNS", DbType="NVarChar(240)")]
		public string DNS
		{
			get
			{
				return this._DNS;
			}
			set
			{
				if ((this._DNS != value))
				{
					this._DNS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Porta", DbType="Int")]
		public System.Nullable<int> Porta
		{
			get
			{
				return this._Porta;
			}
			set
			{
				if ((this._Porta != value))
				{
					this._Porta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UtilizadorBD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UtilizadorBD
		{
			get
			{
				return this._UtilizadorBD;
			}
			set
			{
				if ((this._UtilizadorBD != value))
				{
					this._UtilizadorBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordBD", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PasswordBD
		{
			get
			{
				return this._PasswordBD;
			}
			set
			{
				if ((this._PasswordBD != value))
				{
					this._PasswordBD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAdmin", DbType="NVarChar(50)")]
		public string PasswordAdmin
		{
			get
			{
				return this._PasswordAdmin;
			}
			set
			{
				if ((this._PasswordAdmin != value))
				{
					this._PasswordAdmin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClinicaMulti", DbType="Int")]
		public System.Nullable<int> idClinicaMulti
		{
			get
			{
				return this._idClinicaMulti;
			}
			set
			{
				if ((this._idClinicaMulti != value))
				{
					this._idClinicaMulti = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIM", DbType="Time")]
		public System.Nullable<System.TimeSpan> HIM
		{
			get
			{
				return this._HIM;
			}
			set
			{
				if ((this._HIM != value))
				{
					this._HIM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HFM", DbType="Time")]
		public System.Nullable<System.TimeSpan> HFM
		{
			get
			{
				return this._HFM;
			}
			set
			{
				if ((this._HFM != value))
				{
					this._HFM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HIT", DbType="Time")]
		public System.Nullable<System.TimeSpan> HIT
		{
			get
			{
				return this._HIT;
			}
			set
			{
				if ((this._HIT != value))
				{
					this._HIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HFT", DbType="Time")]
		public System.Nullable<System.TimeSpan> HFT
		{
			get
			{
				return this._HFT;
			}
			set
			{
				if ((this._HFT != value))
				{
					this._HFT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
