<?xml version="1.0" encoding="utf-8"?><Database Name="DigitalSignage" Class="PlayersLigadosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SERVERDEV;Initial Catalog=DigitalSignage;User ID=cliente" SettingsObjectName="Client.Properties.Settings" SettingsPropertyName="DigitalSignageConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Player" Member="Players">
    <Type Name="Player">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="idClinica" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="privateIPAddress" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="publicIPAddress" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="privatePort" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="publicPort" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="privateHostname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="publicHostname" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="wcfEndpoint" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>